---
- name: Set filename of zip if target host is Ubuntu
  ansible.builtin.set_fact:
    zip_file: mqadv_dev{{ version }}_ubuntu_x86-64.tar.gz
  when: ansible_distribution == 'Ubuntu'

- name: Set filename of zip if target host is RedHat
  ansible.builtin.set_fact:
    zip_file: mqadv_dev{{ version }}_linux_x86-64.tar.gz
  when: ansible_distribution == 'RedHat'

- name: Download MQ Advanced for Developers
  ansible.builtin.get_url:
    url: "{{ downloadURL }}{{ zip_file }}"
    dest: /var/mq.tar.gz
    force: false
    mode: "0644"
  tags: download

- name: Extract MQ fom TAR
  ansible.builtin.unarchive:
    src: /var/mq.tar.gz
    remote_src: true
    dest: /var
  tags: download
