---
- name: Including the vars for this platform
  include_vars: "{{ ansible_system }}_{{ role_name }}.yml"

- name: Including the task list for this platform
  include_tasks: "{{ ansible_system }}_{{ role_name }}.yml"
