---
- name: Incrase ssh connection timeout
  command: /usr/sbin/sshd -o ClientAliveInterval=3000
  changed_when: true

- name: Increase space on the disk
  command: chfs -a size=+4G /tmp
  changed_when: true

- name: Increase max_file
  command: huser fsize=-1 root
  changed_when: true
