---
- name: Check if basic registry exists in the install folder
  stat:
    path: /opt/mqm/web/mq/samp/configuration/basic_registry.xml
  register: basic_registry_result

- name: Check if mqwebuser already exists in target folder
  stat:
    path: /var/mqm/web/installations/Installation1/servers/mqweb/mqwebuser.xml
  register: target_mqwebuser_result

- name: Set permissions to allow overwrite of target mqwebuser.xml if it already exists
  become: true
  file:
    path: /var/mqm/web/installations/Installation1/servers/mqweb/mqwebuser.xml
    mode: "0640"
  when: target_mqwebuser_result.stat.exists

- name: Copying basic registry
  become: true
  copy:
    src: /opt/mqm/web/mq/samp/configuration/basic_registry.xml
    dest: /var/mqm/web/installations/Installation1/servers/mqweb/mqwebuser.xml
    remote_src: true
    mode: "0644"
  when: basic_registry_result.stat.exists

- name: Ensure correct permissions for mqwebuser.xml to allow setmqweb commands
  become: true
  file:
    path: /var/mqm/web/installations/Installation1/servers/mqweb/mqwebuser.xml
    mode: "0640"
