---
- name: prepares MQ server
  hosts: mqservers
  become: true
  environment:
    PATH: /opt/mqm/bin:{{ ansible_env.PATH }}
  collections:
    - ibm.ibmmq

  tasks:
    - name: Import downloadmq role
      ansible.builtin.import_role:
        name: downloadmq

    - name: Import setupusers role
      ansible.builtin.import_role:
        name: setupusers

    - name: Import installmq role
      ansible.builtin.import_role:
        name: installmq

    - name: Import setupenvironment role
      ansible.builtin.import_role:
        name: setupenvironment

    - name: Create a queue manager
      become_user: mqm
      tags: ["queue"]
      queue_manager:
        qmname: queue_manager_12
        state: present

    - name: Use MQSC File
      become_user: mqm
      queue_manager:
        qmname: queue_manager_12
        state: running
        mqsc_file: files/dev-config.mqsc